### ISSUE TITLE
F-droid build out of date

### ISSUE THREAD

**Issue by JonnyTech** [Windscribe/Android-App#17]
The last build available on F-droid is still on the previous release. Is there any issue with the latest update?

**Comment by JonnyTech** [comment]
https://f-droid.org/en/packages/com.windscribe.vpn

**Comment by BRBsoup** [comment]
I think F-Droid is just pretty slow on getting the newest versions of anything onto the store because they are more concerned with security and privacy; for example every single app version on F Droid official repository have their source code meticulously scrutinized and then the app is actually compiled BY F-Droid cpu clusters which check for all sorts of special flags during the process. During this whole time there is also community and developer discussions. Once all is satisfactory and properly labeled, then it may be put into queue to be pushed onto the repo and out to F-Droid (or other 3rd party app store) users. This process could take anywhere from around a couple of days to around a couple of weeks. Unless the Developer changed something significant about the app or how he publishes it, it could just very well still be held up on the F-Droid Repo side. IzzyOnDroid apps are generally much quicker and auto-posted onto the repo and then will undergo random/manual review over time, which is why many apps are on both Repo's, essentially allowing for easy-labeled bleeding Edge and Stable versions :D

**Comment by BRBsoup** [comment]
> https://f-droid.org/en/packages/com.windscribe.vpn

Check out the app Obtainium, it allows for adding GitHub repo's and a bunch of other sources. It takes a significant amount of configuring compared to other app updaters/app stores, but for when it comes to apps which don't fall into any other easy way to stay auto-updated, then Obtainium truly shines!

**Comment by JonnyTech** [comment]
Thank you, I shall wait then.

**Comment by Ginder-Singh** [comment]
Its now available :sunglasses:

**Comment by Harrier-Du-Bois** [comment]
Sorry to necro this ticket but on my end the issue is occurring again.

Currently installed version is 3.74.1243 and Fdroid doesn't provide any newer build, which is weird because the patch note refers to 3.75.1297.

**Comment by Ginder-Singh** [comment]
@Harrier-Du-Bois 
Check you have updated fdroid app. I see the 3.75 version on fdroid and I am able to install it.

**Comment by Harrier-Du-Bois** [comment]
Thanks for your reply.
As far as I can tell, the latest Fdroid version available is 1.19.1, which is the one running on my phone.
While I think it shouldn't make a difference, I'm running Graphene. I also have Aurora store installed but I've blacklisted Windscribe in that, cause I'd prefer distribution via Fdroid and I have received the Windscribe version currently via that setup.

Let me know if you need anything else, glad to provide you with info or files.

**Comment by JonnyTech** [comment]
All showing good on my device. When was your repo last updated?

Windscribe version:

![100ump7bath0h0da](https://github.com/Windscribe/Android-App/assets/3584732/3c6e2ee3-69f6-495a-b800-419237672e7d)

Fdroid version:

![bkl2mdx8qx8famap](https://github.com/Windscribe/Android-App/assets/3584732/4628cb65-2ea3-4ba8-ba78-953eb14c5d19)

Repo update time:

![hfpqia94gt385kfh](https://github.com/Windscribe/Android-App/assets/3584732/3ae4ef17-bbf6-421d-80ea-5aecfa8a66a6)

**Comment by Harrier-Du-Bois** [comment]
Thanks for looking into this.
Those things appear pretty much the same one my end, as far as I can tell, except for the available Windscribe builds:
![Screenshot_20240308-141254~2](https://github.com/Windscribe/Android-App/assets/89971442/e00d782c-4dd4-4884-8d2e-3d36646e42c0)
![Screenshot_20240308-141344~2](https://github.com/Windscribe/Android-App/assets/89971442/362e796f-32e4-47fd-bebc-5e820c9cb37c)
![Screenshot_20240308-141415~2](https://github.com/Windscribe/Android-App/assets/89971442/4177f80e-8c20-4aa8-b293-6ebd7ccd7f01)

**Comment by Harrier-Du-Bois** [comment]
Thanks for that hint.
Enabling incompatible resulted in an updated, but it still didn't trigger an update notification:
![Screenshot_20240308-143520~2](https://github.com/Windscribe/Android-App/assets/89971442/ac4832bc-c157-4975-a66f-a24379be25dc)
The "open" button changed to "update" tho, so I guess I can trigger the update manually now. But is that how it's supposed to be, having to check manually?

Enabling "unstable" triggered two different updates instantaneously, but still no update prompt for Windscribe.
![Screenshot_20240308-144053~2](https://github.com/Windscribe/Android-App/assets/89971442/c6031349-8815-46a7-8cbd-59c220d939af)

**Comment by Harrier-Du-Bois** [comment]
What I noticed is that for any other app and also in @JonnyTech s screenshot it says suggested next to the latest stable version but mine doesn't exclusively for Windscribe for whatever reason... Could it be something specific to Graphene after all?

**Comment by BRBsoup** [comment]
That's what I was also thinking, it could be that. The suggested and
compatible versions are mostly based on CPU architecture/installed ROM
(i.e. Armv8-64bit/Armv7-32bit/A64-32bit_64binder). Architecture and ROM
matching is a spiders web of its own, but you should make sure which CPU
architecture your phone has and then that the installed ROM is properly
matched to it, and armv8 can run armv7 apps.

Some developers release app packages individually for specific
architectures, and some release "Universal" packages that contain several
versions inside of the file and Android will automatically detect and
install whichever version matches with your Architecture/ROM.

F-Droid will only ask the first time when switching to a different release
because they are different signatures, and then from them on will continue
to update on that version.

As you mentioned Aurora Store, it is also likely that you had it installed
from there. Sometimes an app not installed from F-Droid will have a
different app signature and not properly show up or update etc...

Your issue could be any mix of these things, or something else, but in any
case, once you get the latest version installed from F-Drive, you should be
good going forward now.

**Comment by Harrier-Du-Bois** [comment]
@BRBsoup Thank you very much for your detailed explanation. I see what you mean and I think you hit the nail on its head. While not 100 % sure, I think it's realistic that I installed Windscribe via Aurora and only later found out about the fdroid repo. So I'll update in fdroid or install from scratch and see how that changes things.
Also thanks for the suggestion regarding alternative clients. I was aware they existed but always assumed it's mostly cosmetics, which I'm not really phased by. But if they offer extended functionality I'll be sure to check them out.

Thanks again to everyone who chipped in, it's well appreciated.

**Comment by Harrier-Du-Bois** [comment]
Just for the record, when I tried to update manually, fdroid couldn't execute due to a signature mismatch. After uninstalling, it immediately displayed the "suggested" tag for the 3.75 build and I could install normally. 
Case solved thanks once more.
