### ISSUE TITLE
F-Droid package still on 3.75

### ISSUE THREAD

**Issue by mmwelt** [Windscribe/Android-App#21]
3.76 was released on 12 April.  The F-Droid package[1] is still showing 3.75.  I'm aware that the F-Droid builds typically take a bit longer to get through, but it's been 7 weeks and the update still isn't there.  Is there anything we can do to speed up the process?

[1] https://f-droid.org/en/packages/com.windscribe.vpn/

**Comment by JonnyTech** [comment]
I see that Windscribe v3.77 is released and F-Droid is still on v3.75. @Ginder-Singh I see that you are active here and authored the last build there (https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.windscribe.vpn.yml), are you able to update, please?

**Comment by Ginder-Singh** [comment]
We had to move some networking code to crossplatform wsnet library(Used by desktop too). Android app depends on the latest version which is not in github yet. I am unable to push to fdroid because fdroid requires this part of code to be opensource. I am working on a workaround untill new version of wsnet is opensourced. Give me untill Tuesday and I will update.

**Comment by JonnyTech** [comment]
Thank you @Ginder-Singh, it was simply a curiosity. It is great to have an ETA but there is really no hurry. Nice to know that there is someone looking into it. Take your time, it is ready when it is ready.

**Comment by Ginder-Singh** [comment]
Finally MR is approved & Build 3.77 is ready.
