### ISSUE TITLE
Please Sync F-Droid and Play Store Releases

### ISSUE THREAD

**Issue by tEctutoRIt** [Windscribe/Android-App#25]
Thanks for the awesome VPN app! I’ve noticed that the F-Droid version often lags behind the Play Store release. As a fan of F-Droid, it’s a bit frustrating to miss out on new features and important security updates.

Could you please consider updating the F-Droid version more regularly? Keeping both versions in sync would ensure everyone gets the latest improvements and stays secure.

Thanks for considering this!

**Comment by ticklemyIP** [comment]
F-droid releases tend to lag behind because they need to check, and sign the applications separately with their own keys. The devs should check out [reproducible builds](https://f-droid.org/en/docs/Reproducible_Builds/) for F-droid to avoid using the F-droid signing keys. If pushing updates on F-droid asap is important to the devs maybe maintaining an F-droid repo could be worth it. Emphasis on maintaining since this may cost resources and time.

**Comment by Ginder-Singh** [comment]
Yeah I only make update MR for fdroid once we push new production release on Play store. As mentioned in above comment fdroid could take while to approve with lots of back end forth. In last release we added wsnet library used by All Windscribe apps this uses vcpkg package management. We had few issues building it from source and fdroid took 10+ days to review hence the delay. On other hand we can use prebuilt libs + tools for Playstore which is much faster. So for these reasons I tend to wait until I have all ducks in row before an MR is sent. Once MR is approved it take 3+ days to show up on store too. 
Today we pushed an update to playstore production which is in review & I have MR going for fdroid already.
